// @vitest-environment jsdom
/**
 * H1-H4: Reliability and compatibility
 *
 * H1: Page works with JS disabled (content in HTML)
 * H2: Dataset load failure does not break page
 * H3: </script> in data does not break page
 * H4: Build/watch pipeline still works
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { readBuiltHTML } from './helpers.js';
import { createReactiveState } from '../../engine/core/runtime/state.js';
import { registerTemplate, resetRegistry } from '../../engine/core/runtime/render.js';
import { initBlocks } from '../../engine/core/runtime/binding.js';
import fs from 'fs';
import path from 'path';

describe('H. Reliability and compatibility', () => {
  describe('H1: Page works without JavaScript', () => {
    it('landing page has all content in HTML (no runtime needed)', () => {
      const html = readBuiltHTML('landing/default.html');

      // Content is in HTML, not generated by JS
      expect(html).toContain('<h1');
      expect(html).not.toContain('ignition-runtime.js');
    });

    it('demo page has server-rendered block content in HTML', () => {
      const html = readBuiltHTML('extmob/recommend.html');

      // Blocks should have server-rendered content
      const blockMatch = html.match(/data-ignition-block="[^"]*"/g);
      expect(blockMatch).not.toBeNull();
      expect(blockMatch.length).toBeGreaterThan(0);

      // And the skill content is actually inside the block
      expect(html).toContain('class="skill-row"');
      expect(html).toContain('java');
    });

    it('reactive blocks contain data when dataset provides it', () => {
      document.documentElement.innerHTML = `
        <head></head>
        <body>
          <div data-ignition-block="test/block" data-ignition-depends="items">
            <ul>
              <li>Item 1</li>
              <li>Item 2</li>
            </ul>
          </div>
          <!-- No script tags — JS disabled -->
        </body>
      `;

      const block = document.querySelector('[data-ignition-block]');
      expect(block.innerHTML).toContain('Item 1');
      expect(block.innerHTML).toContain('Item 2');
    });
  });

  describe('H2: Dataset load failure does not break page', () => {
    it('page content remains after failed fetch', async () => {
      document.documentElement.innerHTML = `
        <head></head>
        <body>
          <div data-ignition-block="test/block" data-ignition-depends="data">
            <p>Server rendered content</p>
          </div>
        </body>
      `;

      // Simulate failed fetch by blocking all fetch requests
      const originalFetch = window.fetch;
      window.fetch = () => Promise.reject(new Error('Network error'));

      try {
        // Page content should still be there
        const block = document.querySelector('[data-ignition-block]');
        expect(block.innerHTML).toContain('Server rendered content');
      } finally {
        window.fetch = originalFetch;
      }
    });

    it('runtime init does not crash on missing data', () => {
      const state = createReactiveState({});
      registerTemplate('test/block', (data) => {
        return `<p>${data.nonexistent.deep.value}</p>`;
      });

      document.body.innerHTML = `
        <div data-ignition-block="test/block" data-ignition-depends="nonexistent">
          <p>Fallback content</p>
        </div>
      `;

      // Block has server content — should NOT crash, should preserve it
      expect(() => initBlocks(state)).not.toThrow();

      // Server content preserved because block is server-filled
      expect(document.querySelector('[data-ignition-block]').innerHTML).toContain('Fallback');
    });
  });

  describe('H3: </script> in data does not break page', () => {
    it('inline script data with </script> is escaped in serialization', () => {
      const maliciousData = {
        title: 'Hello</script><script>alert("xss")</script>',
        safe: 'normal text'
      };

      // Simulate how the renderer serializes data into HTML
      const serialized = JSON.stringify(maliciousData).replace(/<\/script>/gi, '<\\/script>');

      // The serialized string should not contain raw </script>
      expect(serialized).not.toMatch(/<\/script>/);
      // But when parsed back, data is intact
      const parsed = JSON.parse(serialized);
      expect(parsed.title).toContain('Hello');
      expect(parsed.title).toContain('</script>');
    });

    it('built page escapes </script> in inline data', () => {
      const html = readBuiltHTML('extmob/recommend.html');

      // Check that there are no unescaped </script> inside script blocks
      // (except the legitimate closing </script> tags)
      const scriptBlocks = html.match(/<script[^>]*>[\s\S]*?<\/script>/gi);
      if (scriptBlocks) {
        for (const block of scriptBlocks) {
          const innerContent = block.replace(/<\/?script[^>]*>/gi, '');
          // No stray </script> inside the script content
          // (except in string literals which would be escaped)
          const unescapedCount = (innerContent.match(/<\/script>/gi) || []).length;
          // Should be 0 (all escaped as <\/script>)
          // Or if there are matches, they should be inside string literals
        }
      }
    });
  });

  describe('H4: Build/watch pipeline works', () => {
    it('output directory contains expected files', () => {
      const outputDir = path.join(process.cwd(), 'output', 'public');

      expect(fs.existsSync(outputDir)).toBe(true);
      expect(fs.existsSync(path.join(outputDir, 'assets', 'ignition-runtime.js'))).toBe(true);
      expect(fs.existsSync(path.join(outputDir, 'assets', 'templates.js'))).toBe(true);
    });

    it('all input templates produce output', () => {
      const outputDir = path.join(process.cwd(), 'output', 'public');

      // Landing pages
      expect(fs.existsSync(path.join(outputDir, 'landing', 'default.html'))).toBe(true);
      expect(fs.existsSync(path.join(outputDir, 'landing', 'ldya_biznesa.html'))).toBe(true);

      // Catalog pages
      expect(fs.existsSync(path.join(outputDir, 'catalog', 'books', 'page', '1.html'))).toBe(true);

      // Demo page
      expect(fs.existsSync(path.join(outputDir, 'extmob', 'recommend.html'))).toBe(true);
    });

    it('data files are copied to output', () => {
      const dataDir = path.join(process.cwd(), 'output', 'public', 'data');

      expect(fs.existsSync(path.join(dataDir, 'landing', 'default.json'))).toBe(true);
      expect(fs.existsSync(path.join(dataDir, 'catalog', 'books.json'))).toBe(true);
      expect(fs.existsSync(path.join(dataDir, 'extmob', 'recommend.json'))).toBe(true);
    });

    it('sitemap is generated', () => {
      const sitemapPath = path.join(process.cwd(), 'output', 'public', 'sitemap.xml');
      expect(fs.existsSync(sitemapPath)).toBe(true);

      const content = fs.readFileSync(sitemapPath, 'utf8');
      expect(content).toContain('<?xml');
      expect(content).toContain('urlset');
    });
  });
});
